
services:
  kong:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kong-gateway
    restart: unless-stopped

    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_VAULTS: "env"

      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr

      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_ADMIN_GUI_URL: http://localhost:8002

      KONG_PLUGINS: bundled,oauth-client-context
      KONG_LOG_LEVEL: debug
      LOCAL_TEST_RS_PRIVATE_KEY: &rs_private_key |
        -----BEGIN PRIVATE KEY-----
        MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC3u6HaTXrk5m2W
        wTVttoD8jxzHGtfkedtIOQaRF+vHZRqDpS4K+vQQOJpcLivfbE7zjBcY4NrIstgT
        DKOg6jq98S1a5eaDoyesikJLgXbGmw7FzBwOaQd1DNJyqQU5vZkTEk/MQznMk6k3
        yYW80CIh4Eax1SU82ktYoQsPz1I92sS0z3tm++roOiQlSRgA63Su6VxsbqfVcH4u
        3AH7WEyZV4L9fkOJ8/B0/ll2rwO+Ydp2QmCg8v1HCYroA7neIMXxmRvO2fwLOSpO
        fDhFEDYwv+rhHl+A2Qe7U6oEWvWd6B/LRdrjh1TS1OQYCG11XTAg8DTzCYHwOZbw
        lWbQ9gCrAgMBAAECggEAEDLYuDhwh1HRg6MRJNUcVif/74XsVtZvgNSWQaCMRw4g
        4k5j2s/5SJzU7x+a+p2/8DT/rE/Wui8aYcORgZRlDW4AA62VPzHZQ5sE8Uc+w4/U
        I5g1OQgFgkpZG4bPUSHoJwhMRMQAiorSNnrr8ZOgDsCJOxCBsfXFAtFf+krbA1zp
        mch3+Dn4cs+BA0bkqbdwZq8c9l9xKTZRZilfrsJfbPdB5NOHbwpLxsRuuSJ6mWC2
        XIS6r/Ht4iAJQqHqEvJPQ+MHLRkN800RIpm6uym5mUGZrQkcOs74vD2DolqobBe+
        NJ42ot92YbveUVEygHaoQ2F6t1zUHLTDMCK7a2TjIQKBgQD9cQYVvG/6fWEui1hx
        s2NUnz1+gwKRde9vC0dxyBvbxwkD5RbjKv0UJF2gv/Ey9HL7KV6YsuhrcyNdkRnh
        rHa0oYyTLjy4bE4BFMnHGl/HJQb7C/u+affsrLDc3qaem53CANYQmJQFyzuUxVJC
        YwKSxtMeFp3ziVY6fgHsab30UwKBgQC5lnVnaFssMiNQCiCAtFEuO9JXETDqTc4J
        LkSkZdTBqjlHtYnVwbCky/doGJq8riOyUc3AdOGjdYfr01x6I3grccwQ0YSVZNUq
        ew3rUri6w/txcZbVBQPcnuKbh8jzuvNWEMapuVtImLv0cXs/0mnS3zhgozJsv/43
        GiUWWsy3SQKBgBkwzLwIWND6+VfY/dd/TxYwJbqXZv/ySvQsmNNUYoB7zgeXE6lM
        so739l5t9Zls9qjEOeTPk45qiU9ZhssJi1r027YdWGe0TCSLXmrt0itHIOR/Emyg
        t8XMfF/XuZP2P73yu1Q29i+FPczRuBVlJfJU1NMeyGBWfD2gHKzU7c6FAoGAa3bJ
        Qvi1mpDpy8YhbgV74Ja5RLtqpLIq9Tv6eWuR2Ba2lmRzjPhcTgDhoUBmEY2QlAg0
        aRYFNj6vVwoLyZnSUu3RKYf5CvzZRoD83WAIIfWsGtOYcH837j9+nmrxHNkLYLHU
        J6FyT0ZJx9ESejFgH8AsCCFX6IsALG4SPbCUTCkCgYBGsNOvoKA6+tiL5TcC1GvN
        BUxUlI/qT56uH8eIop8+UWBBGitzWhzo2kOMcagQ2K93WGdFRyMpQjcaaCNmMol9
        7eveJSsCfcR9t0eqd9PHYpCdHPI2i+4kKSxkcvxUqkaPXR4x+vk6jK34/dbrePMM
        jnOmBD3+NgzJShVMu6Gihw==
        -----END PRIVATE KEY-----
      BILLING_RS_PRIVATE_KEY: *rs_private_key
      ORDERS_RS_PRIVATE_KEY: *rs_private_key
      LOCAL_TEST_ES_PRIVATE_KEY: &es_private_key |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIPMsmJLI3mB7M/bMHpOnWzLuQ2qLagZR1bqBeFDnhAbqoAoGCCqGSM49
        AwEHoUQDQgAEe1+eiBvr/R3Brd1GLbOn0bZdQW1nfgf6Jry93y6+lqZPBD25AsZf
        snohLGEdZhzcduSzxtQK6IHlPyfg+3F0kg==
        -----END EC PRIVATE KEY-----
      BILLING_ES_PRIVATE_KEY: *es_private_key
      ORDERS_ES_PRIVATE_KEY: *es_private_key

    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"

    volumes:
      - ./kong/plugins/oauth-client-context:/usr/local/share/lua/5.1/kong/plugins/oauth-client-context:ro
      - ./config/kong.yml:/etc/kong/kong.yml:ro
      - ./test-keys:/etc/kong/keys:ro

    networks:
      - kong-net

  httpbin:
    image: kong/httpbin:latest
    container_name: httpbin
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
